In [1]:
import numpy as np

# Backpropagation

In [2]:
def relu(x):
    return np.maximum(0, x)

In [3]:
X = np.array([
    [0.1, 0.5, 1.2],
    [0.3, 1.8, -0.3],
    [-0.4, 0.9, 1.4],
])

y_reg = np.array([[1.689],
                  [1.088],
                [0.886]])

y_bin = np.array([[0],
                  [1],
                  [0]])

y_mul = np.array([[1, 0, 0],
                 [0, 1, 0],
                 [1, 0, 0]])

B = X.shape[0]
n = 3

In [4]:
# Primo hidden layer = 4 neuroni

W1 = np.random.randn(4, 3)
b1 = np.random.randn(4)

In [5]:
Z1 = X @ W1.T + b1

In [6]:
A1 = relu(Z1)

In [7]:
# Secondo hidden layer

W2 = np.random.randn(4, 4)
b2 = np.random.randn(4)

In [8]:
Z2 = A1 @ W2.T + b2
A2 = relu(Z2)

# Output Layer

## Regressione

In [9]:
W3 = np.random.randn(1, 4)
b3 = np.random.randn(1)

In [10]:
Y_hat = A2 @ W3.T + b3

In [11]:
print(Y_hat)

[[-8.03814935]
 [-7.52412846]
 [-8.56303499]]


# Backward pass

In [12]:
def mse_loss(y_hat, y):
    return np.mean((y_hat - y) ** 2)

In [13]:
loss = mse_loss(Y_hat, y_reg)

In [14]:
print(loss)

86.0234844508737


In [15]:
dZ3 = (2.0 / B) * (Y_hat - y_reg)

In [16]:
print(dZ3)

[[-6.48476623]
 [-5.74141897]
 [-6.29935666]]


## Classificazione binaria

##  output layer

In [17]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [18]:
def bce_loss_from_logits(z, y):
    a = np.maximum(z, 0)
    return np.mean(a - z * y + np.log1p(np.exp(-np.abs(z))))

In [19]:
Z3 = A2 @ W3.T + b3

In [20]:
p = sigmoid(Z3)

In [21]:
print(p)

[[0.0003228 ]
 [0.00053961]
 [0.000191  ]]


In [22]:
loss = bce_loss_from_logits(Z3, y_bin)

In [23]:
print(loss)

2.508394028293891


In [24]:
dZ3 = (p - y_bin) / B

In [25]:
print(dZ3)

[[ 1.07600583e-04]
 [-3.33153464e-01]
 [ 6.36673744e-05]]


# Classificazione Multiclasse

# output layer

In [26]:
K = 3

In [27]:
def softmax_batch(z):
    z = z - z.max(axis=1, keepdims=True)
    e = np.exp(z)
    return e / e.sum(axis=1, keepdims=True)

In [28]:
W3 = np.random.randn(K, 4)
b3 = np.random.randn(K)

In [29]:
Z3 = A2 @ W3.T + b3

In [30]:
P = softmax_batch(Z3)

In [31]:
print(P)

[[2.84484342e-01 1.15238472e-02 7.03991811e-01]
 [9.86058866e-01 1.93511500e-04 1.37476230e-02]
 [4.30411441e-01 5.98068456e-03 5.63607874e-01]]


In [32]:
def cross_entropy_from_logits(z, y1h):
    z2 = z - np.max(z, axis=1, keepdims=True)
    lse = np.log(np.sum(np.exp(z2), axis=1, keepdims=True))
    log_p = z2 - lse
    return -np.mean(np.sum(y1h * log_p, axis=1, keepdims=True))

In [33]:
loss = cross_entropy_from_logits(Z3, y_mul)

In [34]:
print(loss)

3.5500881235636825


In [35]:
dZ3 = (P - y_mul) / B

In [36]:
print(dZ3)

[[-0.23850522  0.00384128  0.23466394]
 [ 0.32868629 -0.33326883  0.00458254]
 [-0.18986285  0.00199356  0.18786929]]


# Propagazione verso il secondo hidden layer

In [37]:
def relu_deriv(x):
    return (x > 0).astype(x.dtype)

In [38]:
dA2 = dZ3 @ W3

In [39]:
print(dA2)

[[ 0.21818691  1.06340509 -0.41228291 -0.15042462]
 [-0.21177099 -1.45199045  1.03787006 -0.73054024]
 [ 0.17397693  0.84657087 -0.32667494 -0.12278937]]


In [40]:
dZ2 = dA2 * relu_deriv(Z2)

In [41]:
print(dZ2)

[[ 0.          1.06340509 -0.41228291 -0.        ]
 [-0.         -0.          1.03787006 -0.        ]
 [ 0.          0.84657087 -0.32667494 -0.        ]]


In [42]:
dW2 = A1.T @ dZ2

In [43]:
db2 = dZ2.sum(axis=0,  keepdims=True)

In [44]:
print(W2)

[[ 1.37461695 -0.97667749  0.22002674 -0.459491  ]
 [ 0.78817398  0.5173904   1.92443892 -0.61876695]
 [ 0.63050523  0.12691284  1.65859417  0.23955407]
 [-0.16432075 -2.73826331 -0.04625579 -1.51485486]]


In [45]:
print(dW2)

[[ 0.00000000e+00  2.67400791e+00 -1.03421080e+00  0.00000000e+00]
 [ 0.00000000e+00  5.26253511e+00 -9.46286219e-04  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  3.92407783e-01  0.00000000e+00]
 [ 0.00000000e+00  5.36835035e+00  2.39661090e+00  0.00000000e+00]]


In [46]:
print(b2)

[0.74446018 0.30720517 1.30630298 0.37642409]


In [47]:
print(db2)

[[0.         1.90997596 0.2989122  0.        ]]


# Propagazione verso il primo hidden layer

In [48]:
dA1 = dZ2 @ W2

In [49]:
dZ1 = dA1 * relu_deriv(Z1)

In [50]:
dW1 = X.T @ dZ1

In [51]:
db1 = dZ1.sum(axis=0, keepdims=True)

In [52]:
print(W1)

[[-0.4045694  -0.0825533   1.17143689]
 [ 1.46948157  0.55168003  1.27981258]
 [ 0.74754995 -0.31321034 -1.11779538]
 [ 1.60306377  2.30265784  1.10893131]]


In [53]:
print(dW1)

[[-0.12668978 -0.06931649  0.51642157  0.23974596]
 [ 0.70424823  0.84292362  3.0985294  -0.47273295]
 [ 1.33962684  1.11309794 -0.51642157 -1.82562551]]


In [54]:
print(b1)

[-0.1028373   0.91112749  0.38226453  0.0170528 ]


In [55]:
print(db1)

[[ 1.03947656  1.02613902  1.72140522 -1.11022437]]


# Esempio Completo su tutto il dataset (Batch Gradient Descent)

In [56]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression

### Regressione

In [57]:
X, y = make_regression(n_samples=300, n_features=3, noise=15.0, random_state=42) # dataset sintetico

In [58]:
print(f"Dimensione iniziale di y:", y.shape)

Dimensione iniziale di y: (300,)


In [59]:
y = y.reshape(-1,  1) # reshape di y

In [60]:
print(f"Dimensione di y dopo il reshape:", y.shape)

Dimensione di y dopo il reshape: (300, 1)


In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [62]:
B, d = X_train.shape # B = dimensione del batch (tutto il dataset), # d = numero di features

print(f"Batch dimension: {B} | n features = {d}")

Batch dimension: 210 | n features = 3


### 1. Inizializzazione

In [63]:
# 2 hidden layer, da 4 neuroni ciascuno, attivazione ReLU

n_neurons_hidden1 = 20
n_neurons_hidden2 = 20

In [64]:
# Notazione per la matrice dei pesi del generico layer: W.shape = (n_out, n_in)

W1 = np.random.randn(n_neurons_hidden1, d) * 0.1 # Matrice dei pesi dell' hidden layer 1
b1 = np.zeros((1, n_neurons_hidden1)) # array dei bias dell' hidden layer 1

In [65]:
print(f"Dimensioni della matrice dei pesi del layer 1 (Fully connected Layer): {W1.shape}")
print(f"dimensioni vettore bias: {b1.shape}")

Dimensioni della matrice dei pesi del layer 1 (Fully connected Layer): (20, 3)
dimensioni vettore bias: (1, 20)


In [66]:
W2 = np.random.randn(n_neurons_hidden2, n_neurons_hidden1) * 0.1 # Matrice dei pesi dell' hidden layer 2
b2 = np.zeros((1, n_neurons_hidden2)) # array dei bias dell' hidden layer 2

In [67]:
print(f"Dimensioni della matrice dei pesi del layer 2 (Fully connected Layer): {W2.shape}")
print(f"dimensioni vettore bias: {b2.shape}")

Dimensioni della matrice dei pesi del layer 2 (Fully connected Layer): (20, 20)
dimensioni vettore bias: (1, 20)


In [68]:
W3 = np.random.randn(1, n_neurons_hidden2) * 0.1 # Matrice dei pesi dell' hidden layer 3 (output layer)
b3 = np.zeros((1, 1)) # array dei bias dell' hidden layer 3 (output layer)

In [69]:
print(f"Dimensioni della matrice dei pesi del layer 3 (Fully connected Layer, Output): {W3.shape}")
print(f"dimensioni vettore bias: {b3.shape}")

Dimensioni della matrice dei pesi del layer 3 (Fully connected Layer, Output): (1, 20)
dimensioni vettore bias: (1, 1)


### 2. Forward pass

 - Utilizzando la notazione dimensionale (n_out, n_in) per le matrici dei pesi dei layer, è necessario utilizzare la loro trasposta nel forward pass
  - è possibile inoltre notare come la dimensione delle matrici dei pesi e bias di ciascun layer (e quindi il numero dei parametri della rete), siano unicamente influenzate dall'architettura della rete neurale, mentre la dimensione del batch influenza le dimensioni dell'output dei vari livelli (Le matrici Z e A)

In [70]:
Z1 = X_train @ W1.T + b1 # Pre-attivazioni del primo hidden layer
A1 = relu(Z1) # Attivazioni (output) del primo hidden layer

In [71]:
print(f"Dimensioni matrice delle pre attivazioni (Z1) layer 1 (Fully connected Layer): {Z1.shape}")
print(f"Dimensioni matrice delle attivazioni (A1) layer 1 (Fully connected Layer): {A1.shape}")

Dimensioni matrice delle pre attivazioni (Z1) layer 1 (Fully connected Layer): (210, 20)
Dimensioni matrice delle attivazioni (A1) layer 1 (Fully connected Layer): (210, 20)


In [72]:
Z2 = A1 @ W2.T + b2
A2 = relu(Z2)

In [73]:
print(f"Dimensioni matrice delle pre attivazioni (Z2) layer 2 (Fully connected Layer): {Z2.shape}")
print(f"Dimensioni matrice delle attivazioni (A2) layer 2 (Fully connected Layer): {A2.shape}")

Dimensioni matrice delle pre attivazioni (Z2) layer 2 (Fully connected Layer): (210, 20)
Dimensioni matrice delle attivazioni (A2) layer 2 (Fully connected Layer): (210, 20)


In [74]:
Z3 = A2 @ W3.T + b3

In [75]:
print(Z3)

[[ 6.58466114e-03]
 [ 2.87629232e-03]
 [ 3.12019667e-03]
 [ 6.63797022e-03]
 [-1.55284035e-03]
 [ 1.35257492e-02]
 [ 1.07565488e-03]
 [ 2.60597088e-03]
 [ 3.94151041e-02]
 [ 1.93734304e-02]
 [ 8.66690817e-04]
 [ 2.31195173e-03]
 [ 1.06151874e-03]
 [ 6.85318578e-03]
 [-1.42367346e-03]
 [ 2.12843252e-03]
 [ 7.57290251e-03]
 [ 3.49398265e-03]
 [ 2.85353106e-03]
 [ 1.50376213e-03]
 [ 1.06089118e-02]
 [ 5.59659701e-03]
 [-1.02324763e-04]
 [ 8.43005734e-03]
 [ 4.82992821e-03]
 [ 4.26744787e-03]
 [ 6.55118276e-03]
 [ 2.81528681e-03]
 [ 1.30753520e-03]
 [ 7.02935094e-03]
 [ 5.90839791e-03]
 [ 7.18142723e-03]
 [ 2.43656532e-02]
 [ 5.50964068e-03]
 [ 2.50294816e-03]
 [ 1.17339249e-02]
 [ 1.78748749e-03]
 [ 9.87718872e-04]
 [-1.77435026e-03]
 [-2.45952375e-04]
 [ 1.30651663e-02]
 [ 8.21936447e-04]
 [ 8.22234883e-03]
 [ 8.02654959e-03]
 [ 1.25642685e-02]
 [ 4.33858331e-03]
 [-3.49667408e-04]
 [ 1.72845079e-02]
 [ 8.79805983e-03]
 [ 4.63500742e-03]
 [ 4.25695306e-03]
 [ 5.87528973e-03]
 [ 2.1800744

In [76]:
y_hat = Z3 # output della rete, regressione.

In [77]:
print(f"Dimensioni matrice output della rete neurale (Z3) contenente le predizioni finali del modello: {Z3.shape}")

Dimensioni matrice output della rete neurale (Z3) contenente le predizioni finali del modello: (210, 1)


In [78]:
print(f"Predizioni del modello (uguale a Z3 nella regressione):")
print(y_hat.shape)

Predizioni del modello (uguale a Z3 nella regressione):
(210, 1)


### 3. Calcolo della loss
- nell'esempio si lavora su un problema di regressione, pertanto utilizzeremo il MSE come funzione di perdita da minimizzzare

In [79]:
loss = mse_loss(y_hat, y_train) # loss MSE (Mean Squared Error) in regressione

In [80]:
print(f"Loss iniziale: {loss}")

Loss iniziale: 12557.255980879538


### 4. Backward pass

 - Utilizzando la notazione dimensionale (n_out, n_in) per le matrici dei pesi dei layer, non è necessario utilizzare la loro trasposta nel backward pass

In [81]:
dZ3 = (2.0 / B) * (y_hat - y_train) # errore "locale" del layer 3 (output layer)

In [82]:
dW3 = dZ3.T @ A2 # gradiente dei pesi del layer 3

In [83]:
db3 = dZ3.sum(axis=0, keepdims=True) # gradiente dei bias del layer 3

In [84]:
dA2 = dZ3 @ W3

### Output layer

### Secondo hidden layer

In [85]:
dZ2 = dA2 * relu_deriv(Z2) # errore "locale" del layer 2 (secondo hidden layer)

In [86]:
dW2 = dZ2.T @ A1 # gradiente dei pesi del layer 2

In [87]:
db2 = dZ2.sum(axis=0, keepdims=True)

In [88]:
dA1 = dZ2 @ W2

### Primo hidden layer

In [89]:
dZ1 = dA1 * relu_deriv(Z1)  # errore "locale" del layer 1 (primo hidden layer)

In [90]:
dW1 = dZ1.T @ X_train

In [91]:
db1 = dZ1.sum(axis=0, keepdims=True)

# Aggiornamento dei pesi

In [92]:
eta = 0.1
for W, dW, b, db in [(W1, dW1, b1, db1), (W2, dW2, b2, db2), (W3, dW3, b3, db3)]:
    W -= eta * dW
    b -= eta * db

# Secondo forward pass e calcolo della loss con pesi aggiornati

In [93]:
Z1 = X_train @ W1.T + b1 # Pre-attivazioni del primo hidden layer
A1 = relu(Z1) # Attivazioni (output) del primo hidden layer

Z2 = A1 @ W2.T + b2
A2 = relu(Z2)

Z3 = A2 @ W3.T + b3

y_hat = Z3 # output della rete, regressione.

In [94]:
loss = mse_loss(y_hat, y_train) # loss MSE (Mean Squared Error) in regressione

In [95]:
print(f"Loss dopo aggiornamento: {loss}")

Loss dopo aggiornamento: 12446.790630790698


# Mini-batch gradient descent

In [96]:
n_neurons_hidden1 = 20
n_neurons_hidden2 = 20

In [97]:
# Notazione per la matrice dei pesi del generico layer: W.shape = (n_out, n_in)

W1 = np.random.randn(n_neurons_hidden1, d) * 0.1 # Matrice dei pesi dell' hidden layer 1
b1 = np.zeros((1, n_neurons_hidden1)) # array dei bias dell' hidden layer 1

W2 = np.random.randn(n_neurons_hidden2, n_neurons_hidden1) * 0.1 # Matrice dei pesi dell' hidden layer 2
b2 = np.zeros((1, n_neurons_hidden2)) # array dei bias dell' hidden layer 2

W3 = np.random.randn(1, n_neurons_hidden2) * 0.1 # Matrice dei pesi dell' hidden layer 3 (output layer)
b3 = np.zeros((1, 1)) # array dei bias dell' hidden layer 3 (output layer)

In [98]:
print(f"Totale parametri da ottimizzare durante il training:")
print("----------------------------------------------------")

total = 0

for num_layer, layer_params in enumerate([(W1, b1), (W2, b2), (W3, b3)]):
    n_single_weights = layer_params[0].size
    n_biases = layer_params[1].size
    total_layer_params = n_single_weights + n_biases
    total += total_layer_params
    print(f"Layer {num_layer+1} | weights: {n_single_weights} | biases: {n_biases} | tot: {total_layer_params}")
    print("----------------------------------------------------")

print(f"Totale parametri del modello: {total}")

Totale parametri da ottimizzare durante il training:
----------------------------------------------------
Layer 1 | weights: 60 | biases: 20 | tot: 80
----------------------------------------------------
Layer 2 | weights: 400 | biases: 20 | tot: 420
----------------------------------------------------
Layer 3 | weights: 20 | biases: 1 | tot: 21
----------------------------------------------------
Totale parametri del modello: 521


In [ ]:
def iterate_minibatches(xt, yt, size):
    idx = np.arange(xt.shape[0])
    for s in range(0,  len(idx), size):
        e  = s + size
        bs = idx[s:e]
        yield xt[bs], yt[bs]
        
x = True        
lr, batch_size, epochs = 0.0001, 32, 300
for epoch in range(epochs):
    losses = []
    for Xb, Yb in iterate_minibatches(X_train, y_train, batch_size):
        B = Xb.shape[0]

        # Forward Pass
        Z1 = Xb @ W1.T + b1
        A1 = relu(Z1)
        Z2 = A1 @ W2.T + b2
        A2 = relu(Z2)
        Z3 = A2 @ W3.T + b3
        y_hat = Z3

        # calcoliamo la loss

        loss = mse_loss(y_hat, Yb)
        losses.append(loss)

        # Backward pass
        d3 = (2.0 / B) * (y_hat - Yb) # errore "locale" del layer 3 (output layer)
        dW3 = d3.T @ A2
        db3 = d3.sum(axis=0, keepdims=True)

        dA2 = d3 @ W3
        if x:
            print(dA2)
            x = False
        d2 = dA2 * relu_deriv(Z2)
        dW2 = d2.T @ A1
        db2 = d2.sum(axis=0,  keepdims=True)

        dA1 = d2 @ W2
        d1 = dA1 * relu_deriv(Z1)
        dW1 = d1.T @ Xb
        db1 = d1.sum(axis=0, keepdims=True)

        # update dei pesi
        for W, dW, b, db in [(W1, dW1, b1, db1), (W2, dW2, b2, db2), (W3, dW3, b3, db3)]:
            W -= lr * dW
            b -= lr * db


[[-0.33725914]
 [-1.03614933]
 [ 0.54271825]
 [ 0.33867998]
 [-0.50020775]
 [ 0.5870219 ]
 [-0.2833682 ]
 [-0.30632031]
 [-0.27773454]
 [-0.89275324]
 [-0.60930921]
 [ 0.26046623]
 [ 1.2904313 ]
 [-1.42989457]
 [ 0.28183645]
 [ 0.95594991]
 [ 0.16589185]
 [ 1.16780595]
 [ 0.13593018]
 [-1.45034139]
 [ 0.67119072]
 [-0.17030077]
 [-0.88117138]
 [-0.73463308]
 [ 1.22929594]
 [-1.36666614]
 [-0.25182868]
 [-1.51672959]
 [ 0.90924799]
 [ 0.08815018]
 [-0.52658428]
 [-0.21009069]]
